{
 "title": "OTEL Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Internal Metrics from Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "count by(__name__) ({job=\"prometheus\"})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by(__name__) ({job=\"prometheus\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal Metrics from OTEL Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "count by(__name__) ({job=\"otel-collector-internal\"})",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count by(__name__) ({job=\"otel-collector-internal\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics from OTEL Collector Prometheus Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "count by(__name__) ({job=\"otel-collector-prom-exporter\"})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count by(__name__) ({job=\"otel-collector-prom-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum of instrumented metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(__name__, exported_job) ({job=\"otel-collector-prom-exporter\", exported_job=~\".+\"})",
     "legendFormat": "{{__name__}}: {{exported_job}}"
    }
   ]
  },
  {
   "title": "Rate of instrumented counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(default_dice_rolls_total{job=\"otel-collector-prom-exporter\", exported_job=~\".+\"} [$__rate_interval]))",
     "legendFormat": "default_dice_rolls_total"
    },
    {
     "expr": "sum(rate(default_dice_rolls_value_total{job=\"otel-collector-prom-exporter\", exported_job=~\".+\"} [$__rate_interval]))",
     "legendFormat": "default_dice_rolls_value_total"
    }
   ]
  }
 ]
}