apiVersion: 1

datasources:
  - name: prom
    type: prometheus
    isDefault: true
    editable: true
    access: proxy # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      queryTimeout: 30s
      timeInterval: 5s
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.50.x"
      cacheLevel: None
      disableRecordingRules: false
      # incrementalQueryOverlapWindow: 10m
      # exemplarTraceIdDestinations:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
